scantool script now processing multiple files

diff --git a/scantool b/scantool
--- a/scantool
+++ b/scantool
@@ -12,7 +12,8 @@ usage()
 	echo >&2 ""
 	echo >&2 "$progname:" "$@"
         cat << MESSAGE1
-USAGE: $progname frames | invert | both [-d] [-dd] [-n number] [-p name] [-fb R,G,B] [-dmax value] [+z] [-k] infile [outfile_prefix]
+USAGE: $progname frames | invert | both [-d] [-dd] [-n number] [-p name] [-fb R,G,B] [-dmax value] [+z] [-k] infile outfile_prefix
+USAGE: $progname frames | invert | both [-d] [-dd] [-n number] [-p name] [-fb R,G,B] [-dmax value] [+z] [-k] infile1 infile2 ... outfile_prefix
 USAGE: $progname [-h ]  [-help]
 
 OPTIONS:
@@ -151,71 +152,82 @@ do
     shift   # next option
 done
 
-infile=$1
-outprefix=$2
 
+infiles=()
+for file in "$@"; do
+    shift
+    if [ -f "$file" ] && [ -r "$file" ]; then
+        DEBUG echo "adding $file to be processed"
+        infiles+=($file)
+    elif [ $# -eq 0 ];then
+        outprefix=$file
+    else
+        echo "Cannot open: $file"
+        exit 1
+    fi
+done
+DEBUG declare -p infiles
 
-if [ -z $infile ]
-then
+if [ ${#infiles[*]} -eq 0 ]; then
     echo "must provide a filename"
     usage
 fi
-if [ ! -f "$infile" -o ! -r "$infile" ]; then
-    echo "Cannot open: $infile"
-    exit 1
-fi
 
 if [ -z $outprefix ]; then
-    outprefix=${infile%".tif"}_frame
-else
-    outprefix=${outprefix%".tif"}
+    echo "must provide a outprefix"
+    usage
 fi
+
+
 tmpfileprefix="$tmpprefix"`date +%N``basename "$outprefix"`
 DEBUG echo tmpfileprefix: $tmpfileprefix
 DEBUG echo outprefix: $outprefix
 
 if [ $mode = "frames" ] || [ $mode = "both" ]; then
-invertfiles=()
-DEBUG set -x;
+    invertfiles=()
+    DEBUG set -x;
 
-    #because the strips of film will contain at some gaps the fuzz threshhold can be increased
-    mapfile files < <(vtrimscan vstrip -f 4 $infile $tmpfileprefix | sed 's/^cropping //g' )
-    DEBUG echo files: ${files[*]}
+    for infile in "${infiles[@]}"; do
+        echo processing $infile
+        #because the strips of film will contain at some gaps the fuzz threshhold can be increased
+        mapfile files < <(vtrimscan vstrip -f 4 $infile $tmpfileprefix | sed 's/^cropping //g' )
+        DEBUG echo files: ${files[*]}
 
 
-    for ((i=0;i<${#files[*]};i++)); do
+        for ((i=0;i<${#files[*]};i++)); do
 
-        mapfile filesJ < <(vtrimscan ends -r 90 -f 2 ${files[i]} | grep -v orientating | sed 's/^cropping //g' )
-        DEBUG echo files j:${filesJ[*]}
-        for ((j=0;j<${#filesJ[*]};j++)); do
-            mapfile filesK < <(vtrimscan gap $fuzz $zip ${filesJ[j]} | sed 's/^cropping //g' )
-            DEBUG echo files k:${filesK[*]}
-            for ((k=0;k<${#filesK[*]};k++)); do
-                mkdir -p "$outprefix"
-                outfile="$outprefix"/"$outprefix"-`printf "%03d" "$framenumber"`.tif
-                framenumber=$((framenumber+1))
-                mv ${filesK[k]} $outfile
-                if [ "$debug" -gt 0 ]; then
-                    ln -f $outfile ${filesK[k]}
+            mapfile filesJ < <(vtrimscan ends -r 90 -f 2 ${files[i]} | grep -v orientating | sed 's/^cropping //g' )
+            DEBUG echo files j:${filesJ[*]}
+            for ((j=0;j<${#filesJ[*]};j++)); do
+                mapfile filesK < <(vtrimscan gap $fuzz $zip ${filesJ[j]} | sed 's/^cropping //g' )
+                DEBUG echo files k:${filesK[*]}
+                for ((k=0;k<${#filesK[*]};k++)); do
+                    mkdir -p "$outprefix"
+                    outfile="$outprefix"/"$outprefix"-`printf "%03d" "$framenumber"`.tif
+                    framenumber=$((framenumber+1))
+                    mv ${filesK[k]} $outfile
+                    if [ "$debug" -gt 0 ]; then
+                        ln -f $outfile ${filesK[k]}
+                    fi
+                    echo saving $outfile
+                    invertfiles+=($outfile)
+                done
+                if [ "$keep" -eq 1 ]; then
+                    mkdir -p "$outprefix"
+                    outfile="$outprefix"/"$outprefix"-strip-`printf "%03d" "$stripnumber"`.tif
+                    stripnumber=$((stripnumber+1))
+                    mv ${filesJ[j]} $outfile
+                    if [ "$debug" -gt 0 ]; then
+                        ln -f $outfile ${filesJ[j]}
+                    fi
+                    echo saving $outfile
                 fi
-                echo saving $outfile
-                invertfiles+=($outfile)
             done
-            if [ "$keep" -eq 1 ]; then
-                mkdir -p "$outprefix"
-                outfile="$outprefix"/"$outprefix"-strip-`printf "%03d" "$stripnumber"`.tif
-                stripnumber=$((stripnumber+1))
-                mv ${filesJ[j]} $outfile
-                if [ "$debug" -gt 0 ]; then
-                    ln -f $outfile ${filesJ[j]}
-                fi
-                echo saving $outfile
-            fi
         done
     done
 fi
 
-if [ $mode = "invert" ] || [ $mode = "both" ]; then
+if [ $mode = "both" ]; then
 
 
     for ((i=0;i<${#invertfiles[*]};i++)); do
